-- =============================================================================
-- DATABASE SCHEMA
-- Multi-Agent SWE Benchmark System
-- =============================================================================
-- Conventions:
--   • All primary keys are UUIDs generated by the application layer (gen_random_uuid()
--     is available as a server-side default fallback only).
--   • Timestamps are stored as TIMESTAMPTZ (UTC).
--   • Monetary amounts are NUMERIC(12,8) to preserve sub-cent precision for
--     per-token costs that accumulate to dollars.
--   • JSON payloads are JSONB for indexability.
--   • All tables are in the "benchmark" schema to isolate from any future
--     co-tenant schemas in the same Postgres instance.
--   • Migrations are managed by Alembic. Each migration file lives in
--     src/db/migrations/versions/ and is named {revision_id}_{slug}.py.
--     The migration history is linear (no branches). The initial migration
--     (0001_initial) creates everything below. Subsequent migrations add
--     columns or indexes only; no destructive DDL is permitted in migrations
--     without an explicit rollback script.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Schema
-- ---------------------------------------------------------------------------

CREATE SCHEMA IF NOT EXISTS benchmark;

SET search_path = benchmark, public;

-- ---------------------------------------------------------------------------
-- Extension (required for gen_random_uuid())
-- ---------------------------------------------------------------------------

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- =============================================================================
-- TABLE: llm_cache
-- =============================================================================
-- Stores the response for every unique (model, canonical-messages-hash) pair.
-- Cache entries are permanent and immutable: the first write wins
-- (ON CONFLICT DO NOTHING). There is no TTL. This is intentional: the cache
-- exists to make benchmark runs reproducible, not to save money on ad-hoc
-- queries.
--
-- cache_key  : SHA-256 hex digest of (model_name || canonical_json(messages)).
--              Computed by src/router/cache.py before every LLM call.
-- content    : The raw text content of the LLM response (assistant turn).
-- tool_calls : JSON array of tool-call objects returned by the model, or NULL
--              if the response contained no tool calls.
-- usage      : JSONB snapshot of TokenUsage {prompt_tokens, completion_tokens}.
-- cost_usd   : Cost computed at write time from the pricing table in
--              config/models.yaml. Stored so that cache hits can report $0
--              while the original cost is still auditable.
-- model      : The fully-qualified model name used for this call
--              (e.g. "openrouter/meta-llama/llama-3-70b-instruct").
-- created_at : Wall-clock time of the first (and only) write.
-- =============================================================================

CREATE TABLE llm_cache (
    cache_key       CHAR(64)        NOT NULL,   -- SHA-256 hex, always 64 chars
    model           TEXT            NOT NULL,
    content         TEXT            NOT NULL,
    tool_calls      JSONB           NULL,
    usage           JSONB           NOT NULL,   -- {prompt_tokens, completion_tokens}
    cost_usd        NUMERIC(12, 8)  NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    CONSTRAINT llm_cache_pk PRIMARY KEY (cache_key),
    CONSTRAINT llm_cache_cost_non_negative CHECK (cost_usd >= 0)
);

COMMENT ON TABLE  llm_cache                IS 'Permanent, immutable LLM response cache keyed on SHA-256(model||messages). First write wins; no TTL.';
COMMENT ON COLUMN llm_cache.cache_key      IS 'SHA-256 hex digest of (model_name || canonical_json(messages)).';
COMMENT ON COLUMN llm_cache.model          IS 'Fully-qualified LiteLLM model name used for this call.';
COMMENT ON COLUMN llm_cache.content        IS 'Raw assistant-turn text content.';
COMMENT ON COLUMN llm_cache.tool_calls     IS 'JSON array of tool-call objects, or NULL if none.';
COMMENT ON COLUMN llm_cache.usage          IS 'TokenUsage snapshot: {prompt_tokens: int, completion_tokens: int}.';
COMMENT ON COLUMN llm_cache.cost_usd       IS 'USD cost computed at write time from config/models.yaml pricing.';

-- No additional indexes needed: cache_key is the PK and the only lookup key.


-- =============================================================================
-- TABLE: trace_events
-- =============================================================================
-- Append-only log of every observable event that occurs during a solver run.
-- Rows are written by src/metrics/trace_store.py and are never updated or
-- deleted. The table is the ground truth for cost accounting, debugging, and
-- dashboard rendering.
--
-- event_type values (open enum stored as TEXT):
--   "llm_call"         – a call to the LLM router (cache hit or miss)
--   "tool_call"        – a successful MCP tool invocation
--   "tool_error"       – a tool call rejected by the allow-list or MCP server
--   "budget_exceeded"  – the budget guard halted the run
--   "cap_hit"          – an iteration cap was reached
--
-- agent_role values:
--   "architect" | "developer" | "tester" | "reviewer" | "system"
--
-- payload: arbitrary JSONB for event-specific data. Schema by event_type:
--   llm_call:        {model, tier, cache_hit, prompt_tokens, completion_tokens,
--                     cost_usd, messages_hash}
--   tool_call:       {server, tool, arguments_hash, exit_code}
--   tool_error:      {server, tool, reason}
--   budget_exceeded: {tokens_used, tokens_cap}
--   cap_hit:         {cap_type: "dev_tester"|"dev_reviewer", iterations}
-- =============================================================================

CREATE TABLE trace_events (
    event_id            UUID            NOT NULL DEFAULT gen_random_uuid(),
    run_id              UUID            NOT NULL,
    task_id             TEXT            NOT NULL,
    agent_role          TEXT            NOT NULL,
    turn_index          INTEGER         NOT NULL,
    event_type          TEXT            NOT NULL,
    model               TEXT            NULL,       -- NULL for non-LLM events
    prompt_tokens       INTEGER         NULL,       -- NULL for non-LLM events
    completion_tokens   INTEGER         NULL,       -- NULL for non-LLM events
    cost_usd            NUMERIC(12, 8)  NULL,       -- NULL for non-LLM events
    cache_hit           BOOLEAN         NOT NULL DEFAULT FALSE,
    payload             JSONB           NOT NULL DEFAULT '{}',
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    CONSTRAINT trace_events_pk
        PRIMARY KEY (event_id),
    CONSTRAINT trace_events_turn_index_non_negative
        CHECK (turn_index >= 0),
    CONSTRAINT trace_events_prompt_tokens_non_negative
        CHECK (prompt_tokens IS NULL OR prompt_tokens >= 0),
    CONSTRAINT trace_events_completion_tokens_non_negative
        CHECK (completion_tokens IS NULL OR completion_tokens >= 0),
    CONSTRAINT trace_events_cost_non_negative
        CHECK (cost_usd IS NULL OR cost_usd >= 0),
    CONSTRAINT trace_events_event_type_valid
        CHECK (event_type IN (
            'llm_call', 'tool_call', 'tool_error', 'budget_exceeded', 'cap_hit'
        )),
    CONSTRAINT trace_events_agent_role_valid
        CHECK (agent_role IN (
            'architect', 'developer', 'tester', 'reviewer', 'system'
        ))
);

COMMENT ON TABLE  trace_events                    IS 'Append-only event log for every observable action in a solver run. Never updated or deleted.';
COMMENT ON COLUMN trace_events.event_id           IS 'UUID primary key, generated by the application.';
COMMENT ON COLUMN trace_events.run_id             IS 'UUID of the benchmark run that produced this event. FK to run_records.run_id (not enforced as FK to allow out-of-order writes).';
COMMENT ON COLUMN trace_events.task_id            IS 'SWE-bench or custom task identifier string.';
COMMENT ON COLUMN trace_events.agent_role         IS 'Which agent produced this event: architect|developer|tester|reviewer|system.';
COMMENT ON COLUMN trace_events.turn_index         IS 'Zero-based index of the agent turn within this run+task.';
COMMENT ON COLUMN trace_events.event_type         IS 'Discriminator: llm_call|tool_call|tool_error|budget_exceeded|cap_hit.';
COMMENT ON COLUMN trace_events.model              IS 'Fully-qualified model name; NULL for non-LLM events.';
COMMENT ON COLUMN trace_events.prompt_tokens      IS 'Input token count; NULL for non-LLM events.';
COMMENT ON COLUMN trace_events.completion_tokens  IS 'Output token count; NULL for non-LLM events.';
COMMENT ON COLUMN trace_events.cost_usd           IS 'USD cost for this call; 0 for cache hits; NULL for non-LLM events.';
COMMENT ON COLUMN trace_events.cache_hit          IS 'TRUE if this LLM call was served from the response cache.';
COMMENT ON COLUMN trace_events.payload            IS 'Event-type-specific JSON data. See table comment for per-type schema.';
COMMENT ON COLUMN trace_events.created_at         IS 'Wall-clock UTC timestamp of the event.';

-- Primary access patterns:
--   1. Fetch all events for a run  → (run_id)
--   2. Fetch all events for a task → (task_id)
--   3. Dashboard cost roll-up      → (run_id) with SUM(cost_usd)
CREATE INDEX trace_events_run_id_idx
    ON trace_events (run_id);

CREATE INDEX trace_events_task_id_idx
    ON trace_events (task_id);

-- Partial index: only LLM events have cost; this index supports cost roll-ups
-- without scanning tool_call / tool_error rows.
CREATE INDEX trace_events_run_id_cost_idx
    ON trace_events (run_id, cost_usd)
    WHERE event_type = 'llm_call';

-- Supports time-series queries in the dashboard (events over time for a run).
CREATE INDEX trace_events_run_id_created_at_idx
    ON trace_events (run_id, created_at);


-- =============================================================================
-- TABLE: run_records
-- =============================================================================
-- One row per (run_id, task_id) pair. Written once by MetricsWriter after the
-- scorer returns. Immutable: ON CONFLICT DO NOTHING. The dashboard reads this
-- table for the comparison table and aggregate plots.
--
-- solver_config: JSON-serialized SolverConfig. Stored as JSONB so the dashboard
--   can filter by individual config fields (e.g. solver="multi") without
--   deserializing in Python.
--
-- outcome: "PASS" | "FAIL" — the deterministic scorer's verdict.
--
-- hallucination_score: float in [0.0, 1.0] from HallucinationChecker.
--   0.0 = no hallucinated references; 1.0 = all references hallucinated.
--
-- iteration_count: dev_tester_iterations + dev_reviewer_iterations from
--   the final GraphState.
-- =============================================================================

CREATE TABLE run_records (
    run_id                  UUID            NOT NULL,
    task_id                 TEXT            NOT NULL,
    solver_config           JSONB           NOT NULL,
    outcome                 TEXT            NOT NULL,
    total_cost_usd          NUMERIC(12, 8)  NOT NULL DEFAULT 0,
    total_tokens            INTEGER         NOT NULL DEFAULT 0,
    iteration_count         INTEGER         NOT NULL DEFAULT 0,
    hallucination_score     NUMERIC(5, 4)   NOT NULL DEFAULT 0,
    duration_seconds        NUMERIC(10, 3)  NOT NULL DEFAULT 0,
    cap_hit                 BOOLEAN         NOT NULL DEFAULT FALSE,
    budget_exceeded         BOOLEAN         NOT NULL DEFAULT FALSE,
    patch_size_bytes        INTEGER         NULL,    -- byte length of the final unified diff
    created_at              TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    CONSTRAINT run_records_pk
        PRIMARY KEY (run_id, task_id),
    CONSTRAINT run_records_outcome_valid
        CHECK (outcome IN ('PASS', 'FAIL')),
    CONSTRAINT run_records_total_cost_non_negative
        CHECK (total_cost_usd >= 0),
    CONSTRAINT run_records_total_tokens_non_negative
        CHECK (total_tokens >= 0),
    CONSTRAINT run_records_iteration_count_non_negative
        CHECK (iteration_count >= 0),
    CONSTRAINT run_records_hallucination_score_range
        CHECK (hallucination_score >= 0.0 AND hallucination_score <= 1.0),
    CONSTRAINT run_records_duration_non_negative
        CHECK (duration_seconds >= 0)
);

COMMENT ON TABLE  run_records                       IS 'One immutable row per (run_id, task_id). Written once by MetricsWriter; ON CONFLICT DO NOTHING.';
COMMENT ON COLUMN run_records.run_id                IS 'UUID4 generated by benchmark/cli.py at the start of each benchmark run.';
COMMENT ON COLUMN run_records.task_id               IS 'SWE-bench or custom task identifier string.';
COMMENT ON COLUMN run_records.solver_config         IS 'JSON-serialized SolverConfig: {solver, max_dev_tester_iterations, max_dev_reviewer_iterations, max_tokens_per_task}.';
COMMENT ON COLUMN run_records.outcome               IS 'Deterministic scorer verdict: PASS or FAIL.';
COMMENT ON COLUMN run_records.total_cost_usd        IS 'Sum of cost_usd across all trace_events for this (run_id, task_id).';
COMMENT ON COLUMN run_records.total_tokens          IS 'Sum of prompt_tokens + completion_tokens across all LLM trace_events.';
COMMENT ON COLUMN run_records.iteration_count       IS 'dev_tester_iterations + dev_reviewer_iterations from the final GraphState.';
COMMENT ON COLUMN run_records.hallucination_score   IS 'Float [0,1] from HallucinationChecker: fraction of patch references that do not exist in the repo.';
COMMENT ON COLUMN run_records.duration_seconds      IS 'Wall-clock seconds from graph.invoke() start to scorer return.';
COMMENT ON COLUMN run_records.cap_hit               IS 'TRUE if any iteration cap was reached before the graph reached END naturally.';
COMMENT ON COLUMN run_records.budget_exceeded       IS 'TRUE if BudgetGuard halted the run.';
COMMENT ON COLUMN run_records.patch_size_bytes      IS 'Byte length of the final unified diff string; NULL if no patch was produced.';
COMMENT ON COLUMN run_records.created_at            IS 'Wall-clock UTC timestamp when MetricsWriter committed this record.';

-- Primary access patterns:
--   1. Dashboard comparison table: all records for a run  → (run_id)
--   2. Dashboard filter by solver type                    → (solver_config->>'solver')
--   3. Aggregate pass-rate by solver                      → (outcome, solver_config)
CREATE INDEX run_records_run_id_idx
    ON run_records (run_id);

CREATE INDEX run_records_task_id_idx
    ON run_records (task_id);

-- Supports dashboard filter: "show only multi-agent runs"
CREATE INDEX run_records_solver_idx
    ON run_records ((solver_config->>'solver'));

-- Supports time-ordered listing of runs in the dashboard.
CREATE INDEX run_records_created_at_idx
    ON run_records (created_at DESC);

-- Supports aggregate queries: pass-rate per solver type.
CREATE INDEX run_records_outcome_solver_idx
    ON run_records (outcome, (solver_config->>'solver'));


-- =============================================================================
-- VIEW: run_summary
-- =============================================================================
-- Convenience view used by the Streamlit dashboard and ad-hoc psql queries.
-- Aggregates per-run statistics across all tasks in that run.
-- Not materialised: the dataset is small enough that a live view is fine.
-- =============================================================================

CREATE VIEW run_summary AS
SELECT
    r.run_id,
    r.solver_config->>'solver'                          AS solver,
    COUNT(*)                                            AS total_tasks,
    SUM(CASE WHEN r.outcome = 'PASS' THEN 1 ELSE 0 END) AS tasks_passed,
    ROUND(
        SUM(CASE WHEN r.outcome = 'PASS' THEN 1 ELSE 0 END)::NUMERIC
        / NULLIF(COUNT(*), 0) * 100,
        2
    )                                                   AS pass_rate_pct,
    SUM(r.total_cost_usd)                               AS total_cost_usd,
    SUM(r.total_tokens)                                 AS total_tokens,
    ROUND(AVG(r.iteration_count), 2)                    AS avg_iterations,
    ROUND(AVG(r.hallucination_score), 4)                AS avg_hallucination_score,
    ROUND(AVG(r.duration_seconds), 2)                   AS avg_duration_seconds,
    SUM(CASE WHEN r.cap_hit        THEN 1 ELSE 0 END)   AS cap_hit_count,
    SUM(CASE WHEN r.budget_exceeded THEN 1 ELSE 0 END)  AS budget_exceeded_count,
    MIN(r.created_at)                                   AS run_started_at,
    MAX(r.created_at)                                   AS run_finished_at
FROM run_records r
GROUP BY r.run_id, r.solver_config->>'solver';

COMMENT ON VIEW run_summary IS 'Per-run aggregate statistics across all tasks. Used by the Streamlit dashboard comparison table.';


-- =============================================================================
-- VIEW: task_cost_breakdown
-- =============================================================================
-- Per-(run_id, task_id, agent_role) cost and token breakdown.
-- Used by the dashboard drill-down panel.
-- =============================================================================

CREATE VIEW task_cost_breakdown AS
SELECT
    te.run_id,
    te.task_id,
    te.agent_role,
    COUNT(*)                            AS llm_call_count,
    SUM(te.prompt_tokens)               AS total_prompt_tokens,
    SUM(te.completion_tokens)           AS total_completion_tokens,
    SUM(te.cost_usd)                    AS total_cost_usd,
    SUM(CASE WHEN te.cache_hit THEN 1 ELSE 0 END) AS cache_hit_count
FROM trace_events te
WHERE te.event_type = 'llm_call'
GROUP BY te.run_id, te.task_id, te.agent_role;

COMMENT ON VIEW task_cost_breakdown IS 'Per-(run_id, task_id, agent_role) LLM cost and token breakdown for dashboard drill-down.';


-- =============================================================================
-- MIGRATIONS STRUCTURE NOTE
-- =============================================================================
-- Alembic migration files live in src/db/migrations/versions/.
-- The env.py target_metadata points to src/db/schema.py Base.metadata.
-- Migration naming convention: {4-digit-sequence}_{short_slug}.py
--
-- Planned migration history:
--
--   0001_initial.py
--       • Creates schema "benchmark"
--       • Creates extension pgcrypto
--       • Creates tables: llm_cache, trace_events, run_records
--       • Creates all indexes listed above
--       • Creates views: run_summary, task_cost_breakdown
--       • Downgrade: drops views, indexes, tables, schema (in reverse order)
--
--   Future migrations (examples, not yet created):
--
--   0002_add_patch_diff_table.py
--       • Adds table "patch_diffs" to store full patch text separately from
--         run_records, avoiding bloat in the main table.
--       • run_records.patch_size_bytes remains; full text moves here.
--       • Downgrade: drop table patch_diffs.
--
--   0003_add_trace_events_agent_role_idx.py
--       • Adds index on trace_events(run_id, agent_role) if dashboard queries
--         show sequential scans on agent_role filters.
--       • Downgrade: drop index.
--
-- Rules for all future migrations:
--   • No DROP COLUMN, DROP TABLE, or ALTER COLUMN TYPE without a paired
--     rollback script in src/db/migrations/rollbacks/.
--   • No migration may modify existing CHECK constraints in a way that
--     invalidates existing rows.
--   • Every migration must be idempotent when run twice (use IF NOT EXISTS /
--     IF EXISTS guards or Alembic's op.execute with conditional logic).
-- =============================================================================